#!/bin/bash

N_SYM=1000
N_VERTEX=8000
MAX_SUCC=4
N_ACTIVE=10
N_THREAD=6
PRINT_OUTPUT=t
PRINT_INPUT=t


make clean && (cd spu; make) && make XTRACFLAGS=-DUSE_CELL
./dataflow $N_SYM $N_VERTEX $MAX_SUCC $N_ACTIVE $N_THREAD $PRINT_OUTPUT $PRINT_INPUT > cell-with-cell_output.txt
# make clean && (cd spu; make) && make XTRACFLAGS=-DUSE_CELL; ./dataflow 100 8 4 10 1 t t

make clean && (cd spu; make) && make
./dataflow $N_SYM $N_VERTEX $MAX_SUCC $N_ACTIVE $N_THREAD $PRINT_OUTPUT $PRINT_INPUT > cell-no-cell_output.txt
# make clean && (cd spu; make) && make; ./dataflow 100 8 4 10 1 t t

#(cd ../lab4; make)
# ../lab4/dataflow 100 8 4 10 1 t t > c_output.txt

#diff c_output.txt cell-no-cell_output.txt
diff cell-with-cell_output.txt cell-no-cell_output.txt

